/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VoiceSetting = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const AccentSetting = IDL.Variant({
  'uk' : IDL.Null,
  'us' : IDL.Null,
  'african' : IDL.Null,
});
export const SpeedSetting = IDL.Variant({
  'normal' : IDL.Null,
  'fast' : IDL.Null,
  'slow' : IDL.Null,
});
export const Time = IDL.Int;
export const HistoryEntry = IDL.Record({
  'id' : IDL.Nat,
  'accent' : AccentSetting,
  'inputText' : IDL.Text,
  'voice' : VoiceSetting,
  'speed' : SpeedSetting,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addHistoryEntry' : IDL.Func(
      [IDL.Text, VoiceSetting, AccentSetting, SpeedSetting],
      [IDL.Nat],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [HistoryEntry], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VoiceSetting = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const AccentSetting = IDL.Variant({
    'uk' : IDL.Null,
    'us' : IDL.Null,
    'african' : IDL.Null,
  });
  const SpeedSetting = IDL.Variant({
    'normal' : IDL.Null,
    'fast' : IDL.Null,
    'slow' : IDL.Null,
  });
  const Time = IDL.Int;
  const HistoryEntry = IDL.Record({
    'id' : IDL.Nat,
    'accent' : AccentSetting,
    'inputText' : IDL.Text,
    'voice' : VoiceSetting,
    'speed' : SpeedSetting,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addHistoryEntry' : IDL.Func(
        [IDL.Text, VoiceSetting, AccentSetting, SpeedSetting],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [HistoryEntry], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };