/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccentSetting = { 'uk' : null } |
  { 'us' : null } |
  { 'african' : null };
export interface HistoryEntry {
  'id' : bigint,
  'accent' : AccentSetting,
  'inputText' : string,
  'voice' : VoiceSetting,
  'speed' : SpeedSetting,
  'timestamp' : Time,
}
export type SpeedSetting = { 'normal' : null } |
  { 'fast' : null } |
  { 'slow' : null };
export type Time = bigint;
export type VoiceSetting = { 'female' : null } |
  { 'male' : null };
export interface _SERVICE {
  'addHistoryEntry' : ActorMethod<
    [string, VoiceSetting, AccentSetting, SpeedSetting],
    bigint
  >,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getAllEntries' : ActorMethod<[], Array<HistoryEntry>>,
  'getEntry' : ActorMethod<[bigint], HistoryEntry>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];