/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface HistoryEntry {
    id: bigint;
    accent: AccentSetting;
    inputText: string;
    voice: VoiceSetting;
    speed: SpeedSetting;
    timestamp: Time;
}
export enum AccentSetting {
    uk = "uk",
    us = "us",
    african = "african"
}
export enum SpeedSetting {
    normal = "normal",
    fast = "fast",
    slow = "slow"
}
export enum VoiceSetting {
    female = "female",
    male = "male"
}
export interface backendInterface {
    addHistoryEntry(inputText: string, voice: VoiceSetting, accent: AccentSetting, speed: SpeedSetting): Promise<bigint>;
    deleteEntry(id: bigint): Promise<void>;
    getAllEntries(): Promise<Array<HistoryEntry>>;
    getEntry(id: bigint): Promise<HistoryEntry>;
}
import type { AccentSetting as _AccentSetting, HistoryEntry as _HistoryEntry, SpeedSetting as _SpeedSetting, Time as _Time, VoiceSetting as _VoiceSetting } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addHistoryEntry(arg0: string, arg1: VoiceSetting, arg2: AccentSetting, arg3: SpeedSetting): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addHistoryEntry(arg0, to_candid_VoiceSetting_n1(this._uploadFile, this._downloadFile, arg1), to_candid_AccentSetting_n3(this._uploadFile, this._downloadFile, arg2), to_candid_SpeedSetting_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHistoryEntry(arg0, to_candid_VoiceSetting_n1(this._uploadFile, this._downloadFile, arg1), to_candid_AccentSetting_n3(this._uploadFile, this._downloadFile, arg2), to_candid_SpeedSetting_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deleteEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async getAllEntries(): Promise<Array<HistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntries();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntries();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntry(arg0: bigint): Promise<HistoryEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntry(arg0);
                return from_candid_HistoryEntry_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntry(arg0);
            return from_candid_HistoryEntry_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccentSetting_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccentSetting): AccentSetting {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HistoryEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoryEntry): HistoryEntry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SpeedSetting_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpeedSetting): SpeedSetting {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_VoiceSetting_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoiceSetting): VoiceSetting {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    accent: _AccentSetting;
    inputText: string;
    voice: _VoiceSetting;
    speed: _SpeedSetting;
    timestamp: _Time;
}): {
    id: bigint;
    accent: AccentSetting;
    inputText: string;
    voice: VoiceSetting;
    speed: SpeedSetting;
    timestamp: Time;
} {
    return {
        id: value.id,
        accent: from_candid_AccentSetting_n10(_uploadFile, _downloadFile, value.accent),
        inputText: value.inputText,
        voice: from_candid_VoiceSetting_n12(_uploadFile, _downloadFile, value.voice),
        speed: from_candid_SpeedSetting_n14(_uploadFile, _downloadFile, value.speed),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uk: null;
} | {
    us: null;
} | {
    african: null;
}): AccentSetting {
    return "uk" in value ? AccentSetting.uk : "us" in value ? AccentSetting.us : "african" in value ? AccentSetting.african : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): VoiceSetting {
    return "female" in value ? VoiceSetting.female : "male" in value ? VoiceSetting.male : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    fast: null;
} | {
    slow: null;
}): SpeedSetting {
    return "normal" in value ? SpeedSetting.normal : "fast" in value ? SpeedSetting.fast : "slow" in value ? SpeedSetting.slow : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HistoryEntry>): Array<HistoryEntry> {
    return value.map((x)=>from_candid_HistoryEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AccentSetting_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccentSetting): _AccentSetting {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SpeedSetting_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpeedSetting): _SpeedSetting {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_VoiceSetting_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceSetting): _VoiceSetting {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VoiceSetting): {
    female: null;
} | {
    male: null;
} {
    return value == VoiceSetting.female ? {
        female: null
    } : value == VoiceSetting.male ? {
        male: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccentSetting): {
    uk: null;
} | {
    us: null;
} | {
    african: null;
} {
    return value == AccentSetting.uk ? {
        uk: null
    } : value == AccentSetting.us ? {
        us: null
    } : value == AccentSetting.african ? {
        african: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpeedSetting): {
    normal: null;
} | {
    fast: null;
} | {
    slow: null;
} {
    return value == SpeedSetting.normal ? {
        normal: null
    } : value == SpeedSetting.fast ? {
        fast: null
    } : value == SpeedSetting.slow ? {
        slow: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
